INSERT INTO bears (name, age, gender, color, temperament, alive)
INSERT INTO bears (name, age, gender, color, temperament, alive)
INSERT INTO bears (name, age, gender, color, temperament, alive)
INSERT INTO bears (name, age, gender, color, temperament, alive)
INSERT INTO bears (name, age, gender, color, temperament, alive)
INSERT INTO bears (name, age, gender, color, temperament, alive)
INSERT INTO bears (name, age, gender, color, temperament, alive)
INSERT INTO bears (name, age, gender, color, temperament, alive)